- hosts: localhost
  connection: local
  pre_tasks:

  - name: Create frontend instance
    include_role:
       name: osp-instances
       vars_from: frontend.yaml
  
  - name: Create app1 instance
    include_role:
       name: osp-instances
       vars_from: app1.yaml

  - name: Create app2 instance
    include_role:
       name: osp-instances
       vars_from: app2.yaml

  - name: Create frontend instance
    include_role:
       name: osp-instances
       vars_from: app1.yaml              

  - name: Create frontend instance
    include_role:
       name: osp-instances
       vars_from: db.yaml

  roles:
   -  osp-setup
   -  osp-provision-instance